CONFIG_ZMK_USB_LOGGING=n

# Battery level thresholds for LED color
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=70
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=20
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

# Show a battery level based color when charging
CONFIG_CHG_POLICY=n
CONFIG_CHG_BATTERY_LEVEL_BASED_COLOR=y
CONFIG_CHG_BATTERY_LEVEL_HIGH=90
CONFIG_CHG_BATTERY_LEVEL_LOW=20
CONFIG_CHG_BATTERY_LEVEL_CRITICAL=5
CONFIG_CHG_BATTERY_COLOR_HIGH=2
CONFIG_CHG_BATTERY_COLOR_MEDIUM=3
CONFIG_CHG_BATTERY_COLOR_LOW=1
CONFIG_CHG_BATTERY_COLOR_CRITICAL=5
CONFIG_CHG_BATTERY_COLOR_MISSING=0